"""
F.R.I.D.A.Y. 3.0 — Deep Research 2.0 Synthesizer
Synthesizes cross-checked findings, contradictions, and citations into a formal ResearchBriefing.
"""

from typing import List
from friday_core.research.models import (
    ResearchSource,
    KeyFinding,
    Contradiction,
    ResearchBriefing
)


class DeepResearchSynthesizer:
    """
    Synthesizes verified findings, detected contradictions, and source citations
    into executive research briefings.
    """

    @classmethod
    def synthesize(
        cls,
        topic: str,
        findings: List[KeyFinding],
        contradictions: List[Contradiction],
        sources: List[ResearchSource]
    ) -> ResearchBriefing:
        """
        Builds a verified ResearchBriefing data structure.
        """
        if not sources or not findings:
            return ResearchBriefing(
                topic=topic,
                executive_summary="No verifiable multi-source intelligence could be extracted for this topic.",
                findings=[],
                contradictions=contradictions,
                sources=sources,
                is_verified=False
            )

        top_findings = findings[:5]
        exec_summary_points = [f"- {f.claim} (Confidence: {int(f.confidence * 100)}%)" for f in top_findings]
        summary = f"Executive briefing for '{topic}':\n" + "\n".join(exec_summary_points)

        if contradictions:
            summary += f"\n\nNote: {len(contradictions)} contrasting or conflicting claims were detected across consulted sources."

        is_verified = len(findings) > 0 and (len(sources) >= 1)

        return ResearchBriefing(
            topic=topic,
            executive_summary=summary,
            findings=findings,
            contradictions=contradictions,
            sources=sources,
            is_verified=is_verified
        )

    @classmethod
    def format_markdown(cls, briefing: ResearchBriefing) -> str:
        """Renders briefing into clean GitHub-flavored markdown with clickable citations."""
        lines = [
            f"# Research Dossier: {briefing.topic.title()}",
            f"*Generated by F.R.I.D.A.Y. 3.0 Intelligence Engine at {briefing.created_at}*",
            "",
            "## Executive Summary",
            briefing.executive_summary,
            "",
            "## Key Findings"
        ]

        if not briefing.findings:
            lines.append("*(No corroborated findings)*")
        else:
            for idx, f in enumerate(briefing.findings[:8], 1):
                sources_str = ", ".join([f"[Source]({url})" for url in f.supporting_sources])
                lines.append(f"{idx}. **{f.claim}**")
                lines.append(f"   - *Confidence*: {int(f.confidence * 100)}% | *Citations*: {sources_str}")

        if briefing.contradictions:
            lines.extend(["", "## Flagged Contradictions & Discrepancies"])
            for c in briefing.contradictions:
                lines.append(f"- **{c.topic}**:")
                lines.append(f"  - Source A ({c.source_a}): \"{c.claim_a}\"")
                lines.append(f"  - Source B ({c.source_b}): \"{c.claim_b}\"")

        lines.extend(["", "## Consulted Sources"])
        for s in briefing.sources:
            lines.append(f"- [{s.title}]({s.url}) (Credibility: {s.credibility_score})")

        return "\n".join(lines)
